services:
  music-bot:
    tty: true
    build:
      context: .
      dockerfile : Dockerfile
    
    env_file:
      - .env 
    
    volumes:
      - type: bind
        source: .
        target: /home/music-bot/

    restart: always

    command: python src/bot.py